const menus={coffee:[['house-espresso','House Espresso','Dark chocolate · walnut · caramel',180,'Bestseller'],['flat-white','Flat White','Double espresso · silky milk',240],['seasonal-pour-over','Seasonal Pour Over','Ask us what’s on the bar today',280],['spanish-latte','Spanish Latte','Condensed milk · sea salt',260],['cold-brew-tonic','Cold Brew Tonic','Orange peel · rosemary tonic',280],['ceremonial-matcha','Ceremonial Matcha','Stone-ground matcha · oat or dairy',290]],breakfast:[['serein-breakfast','Serein Breakfast','Eggs · sourdough · greens · roast tomato',520,'Favourite'],['ricotta-toast','Ricotta Toast','Whipped ricotta · fig · wild honey',390],['shakshuka','Shakshuka','Baked eggs · spiced tomato · focaccia',440],['coconut-granola','Coconut Granola','Seasonal fruit · coconut yoghurt',320],['croque-madame','Croque Madame','Smoked ham · gruyère · fried egg',480],['mushroom-rosti','Mushroom Rösti','Potato · brown butter · herbs',420]],bakery:[['almond-croissant','Almond Croissant','Twice-baked · frangipane',250,'Daily'],['sea-salt-cookie','Sea Salt Cookie','Dark chocolate · browned butter',190],['morning-bun','Morning Bun','Cinnamon · orange · cultured butter',220],['basque-cheesecake','Basque Cheesecake','Burnt honey · vanilla bean',320],['olive-oil-cake','Olive Oil Cake','Lemon · rosemary · crème fraîche',280],['sourdough-loaf','Sourdough Loaf','36-hour ferment · stone baked',350]],seasonal:[['mango-burrata','Mango & Burrata','Alphonso · basil oil · sourdough',480,'New'],['peach-iced-tea','Peach Iced Tea','Darjeeling · white peach · mint',240],['summer-pea-risotto','Summer Pea Risotto','Garden peas · parmesan · herbs',520],['charred-corn-tartine','Charred Corn Tartine','Chilli butter · feta · coriander',390],['berry-pavlova','Berry Pavlova','Strawberry · mulberry · cream',330],['watermelon-spritz','Watermelon Spritz','Kokum · lime · sparkling water',240]]};
const grid=document.querySelector('#menuGrid');
function renderMenu(type){grid.innerHTML=menus[type].map(([id,name,desc,price,badge])=>`<article class="menu-item"><div><h3>${name}${badge?`<span class="badge">${badge}</span>`:''}</h3><p>${desc}</p></div><div class="menu-buy"><strong>₹${price}</strong><button type="button" data-add="${id}" data-name="${name}" data-price="${price}" aria-label="Add ${name} to order">+</button></div></article>`).join('')}
renderMenu('coffee');
document.querySelectorAll('.filters button').forEach(btn=>btn.addEventListener('click',()=>{document.querySelector('.filters .active').classList.remove('active');btn.classList.add('active');renderMenu(btn.dataset.filter)}));
const header=document.querySelector('#header');window.addEventListener('scroll',()=>header.classList.toggle('scrolled',scrollY>30));
const toggle=document.querySelector('.menu-toggle'),nav=document.querySelector('#nav');toggle.addEventListener('click',()=>{const open=nav.classList.toggle('open');toggle.classList.toggle('active',open);toggle.setAttribute('aria-expanded',open);document.body.classList.toggle('no-scroll',open)});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');toggle.classList.remove('active');document.body.classList.remove('no-scroll')}));
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
const lightbox=document.querySelector('#lightbox');document.querySelectorAll('.gallery-item').forEach(item=>item.addEventListener('click',()=>{const img=item.querySelector('img');lightbox.querySelector('img').src=img.src;lightbox.querySelector('img').alt=img.alt;lightbox.showModal()}));lightbox.querySelector('button').addEventListener('click',()=>lightbox.close());lightbox.addEventListener('click',e=>{if(e.target===lightbox)lightbox.close()});
const toast=document.querySelector('#toast');function showToast(msg){toast.textContent=msg;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),3500)}
async function postJSON(url,data){const response=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const result=await response.json();if(!response.ok)throw new Error(result.error||'Please try again.');return result}
document.querySelector('#bookingForm').addEventListener('submit',async e=>{e.preventDefault();const button=e.target.querySelector('button');button.disabled=true;button.textContent='Sending…';try{const result=await postJSON('/api/reservations',Object.fromEntries(new FormData(e.target)));showToast(`Table requested · ${result.reference}`);e.target.reset()}catch(err){showToast(err.message)}finally{button.disabled=false;button.innerHTML='Request a table <span>↗</span>'}});
document.querySelector('#newsletter').addEventListener('submit',async e=>{e.preventDefault();try{await postJSON('/api/newsletter',{email:e.target.querySelector('input').value});showToast('Welcome to our little corner of the internet.');e.target.reset()}catch(err){showToast(err.message)}});
const dateInput=document.querySelector('input[type="date"]');dateInput.min=new Date().toISOString().split('T')[0];
document.addEventListener('mousemove',e=>{const glow=document.querySelector('.cursor-glow');glow.style.left=e.clientX+'px';glow.style.top=e.clientY+'px'});

const cart=new Map(),drawer=document.querySelector('#cartDrawer'),backdrop=document.querySelector('#drawerBackdrop');
function openCart(){drawer.classList.add('open');backdrop.classList.add('show');drawer.setAttribute('aria-hidden','false');document.body.classList.add('no-scroll')}
function closeCart(){drawer.classList.remove('open');backdrop.classList.remove('show');drawer.setAttribute('aria-hidden','true');document.body.classList.remove('no-scroll')}
function updateCart(){const items=[...cart.values()],count=items.reduce((s,i)=>s+i.quantity,0),total=items.reduce((s,i)=>s+i.price*i.quantity,0);document.querySelector('#cartCount').textContent=count;document.querySelector('#cartTotal').textContent=`₹${total}`;document.querySelector('#cartCheckout').hidden=!items.length;document.querySelector('#cartItems').innerHTML=items.length?items.map(i=>`<div class="cart-line"><div><strong>${i.name}</strong><small>₹${i.price} each</small></div><div class="quantity"><button data-change="${i.id}" data-delta="-1">−</button><span>${i.quantity}</span><button data-change="${i.id}" data-delta="1">+</button></div></div>`).join(''):'<p class="empty-cart">Your basket is waiting for something delicious.</p>'}
grid.addEventListener('click',e=>{const btn=e.target.closest('[data-add]');if(!btn)return;const item=cart.get(btn.dataset.add)||{id:btn.dataset.add,name:btn.dataset.name,price:Number(btn.dataset.price),quantity:0};item.quantity++;cart.set(item.id,item);updateCart();openCart()});
document.querySelector('#cartItems').addEventListener('click',e=>{const btn=e.target.closest('[data-change]');if(!btn)return;const item=cart.get(btn.dataset.change);item.quantity+=Number(btn.dataset.delta);if(item.quantity<=0)cart.delete(item.id);updateCart()});
document.querySelector('#cartTrigger').addEventListener('click',openCart);document.querySelector('.cart-close').addEventListener('click',closeCart);backdrop.addEventListener('click',closeCart);
document.querySelector('#orderForm').addEventListener('submit',async e=>{e.preventDefault();const button=e.target.querySelector('button');button.disabled=true;button.textContent='Placing order…';try{const data=Object.fromEntries(new FormData(e.target));data.items=[...cart.values()].map(({id,quantity})=>({id,quantity}));const result=await postJSON('/api/orders',data);cart.clear();updateCart();closeCart();e.target.reset();showToast(`Order received · ${result.reference} · ₹${result.total}`)}catch(err){showToast(err.message)}finally{button.disabled=false;button.innerHTML='Place order <span>↗</span>'}});
